index:
  path: /
  controller: App\Controller\MainController::index

categories_main:
  path: /list-of-categories
  controller: App\Controller\MainController::categories

classes_main:
  path: /list-of-classes
  controller: App\Controller\MainController::classes

show_course_main:
  path: /show/course/{slug}
  controller: App\Controller\MainController::course_main

show_category_main:
  path: /show/category/{id}
  controller: App\Controller\MainController::category_main

admin:
  path: /admin
  controller: App\Controller\AdminController::index

category_index:
  path: /category
  controller: App\Controller\CategoryController::index

category_new:
  path: /category/new
  controller: App\Controller\CategoryController::new

category_show:
  path: /category/{id}
  controller: App\Controller\CategoryController::show

category_edit:
  path: /category/{id}/edit
  controller: App\Controller\CategoryController::edit

category_delete:
  path: /category/{id}/delete
  controller: App\Controller\CategoryController::delete

classes_index:
  path: /classes
  controller: App\Controller\ClassesController::index

classes_new:
  path: /classes/new
  controller: App\Controller\ClassesController::new

classes_show:
  path: /classes/{id}
  controller: App\Controller\ClassesController::show

classes_edit:
  path: /classes/{id}/edit
  controller: App\Controller\ClassesController::edit

classes_delete:
  path: /classes/{id}/delete
  controller: App\Controller\ClassesController::delete

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout